In [7]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
dataset = pd.read_csv("breastcancer.csv")
# dataset.head()
# dataset.info()
x = dataset.iloc[:, :-1].values
print(x)
y = dataset.iloc[:, 4].values
print(y)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20)
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
# print(classification_report(y_test, y_pred))
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))
# df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
# df
for(i,j) in zip(y_pred,y_test):
    if i != j:
        print("actual value:",i,"\npredicted value :",j)
print("Number of mislabeled points from test data set :",(y_test != y_pred).sum())


[[1002945       5       4 ...       3       2       1]
 [1015425       3       1 ...       3       1       1]
 [1016277       6       8 ...       3       7       1]
 ...
 [ 888820       5      10 ...       8      10       2]
 [ 897471       4       8 ...      10       6       1]
 [ 897471       4       8 ...      10       4       1]]
[ 5  1  1  3  8  1  1  1  1  1  1  3  1 10  4  1  1  6  1 10  3  1  1  1
  4  1  1  1  1  1  1  3  2  1  1  8  1  9  3  9  1  2  6  4  1  4  1  3
  2  1  4  2  8  6  3  1  1  1  2  5  1  1  1  1  1  1  1  3  1  1  8  2
 10  1  1  1  2  1  1  1  2  1  1  8  1  4  6  1  2  1  2  1  1  1  1  2
  1  2 10  1  4  1  1 10  4  8 10  1  4  2  3 10  3  1  1  1 10  1  1  2
  1  2  1  7  1  7  1  4  1  1  1 10  1  1  1  1  1  1  1  1  1  4  1  1
  1  2  1  3  4  1  1  6  1  1  6  1  1  1  3  4  1  1  2  1  1  8 10  1
  2  1  1  1 10  4  7  1  3  1  3  1  1  1  8  4  1  6 10 10  1  8 10  1
  1  1  1  5  4  1  1  5  4  1  1  1  9  3  1  1  1 10  8  1 10 10  7  1
  1  7 